version: '3.4'

services:
  taskmanager-api:
    build:
      context: .
      dockerfile: TaskManager.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    networks:
      - tasknet

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - tasknet

networks:
  tasknet:
    driver: bridge
